### ISSUE TITLE
Protect the frontend and backend with auth

### ISSUE THREAD

**Issue by BenJeau** [BenJeau/indicator-aggregator#40]
**Is your feature request related to a problem? Please describe.**
Current backend APIs are not protected, meaning anyone/anything can query the backend if they can reach the backend

**Describe the solution you'd like**
Have the following be potentially its own microservice or at least segmented code-wise within its own Rust workspace.

It would be great to support multiple different authentication methods:
- [ ] managed username/password #44 
- [x] openid (e.g. with GitHub, Microsoft, Google as authentication provider) #41 

_We'd need to add authorization support as well as user management._

Authentication should be made using:
- [x] a simple JWT bearer token issued by the backend which encompasses the users data which is valid for a short interval, e.g. 1h #41 
  - [ ] Refresh tokens are _nice_ but not needed for first implementation. #51 
- [x] an API token issued by the backend which links to a user and has the option of having an expiration date #43 

Authorization should be managed within the UI/API:
- [ ] need to create roles for read/write and per sections of the API
- [ ] allow/deny user access to the system
- [ ] activate/deactivate users

After all of this is implemented, we could start linked changes to users, e.g.
- [ ] requests made
- [ ] split quota per user
- [ ] enable a subset of sources/providers/ignoreLists for select users

**Describe alternatives you've considered**

- Use an external third party for authentication, e.g. Auth0, Okta, Firebase, ... - I don't want to force a third party dependency for Authorization/Authentication, it should be optional
- Using Keycloak, ultimately this is not a bad option, but is a bit complex to setup
